/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attachments: typeof import('./src/components/Attachments.vue')['default']
    Bubble: typeof import('./src/components/Bubble.vue')['default']
    Conversations: typeof import('./src/components/Conversations.vue')['default']
    Prompts: typeof import('./src/components/Prompts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sender: typeof import('./src/components/Sender.vue')['default']
    SenderTsx: typeof import('./src/components/SenderTsx.vue')['default']
    Suggestion: typeof import('./src/components/Suggestion.vue')['default']
    ThoughtChain: typeof import('./src/components/ThoughtChain.vue')['default']
    UseXAgent: typeof import('./src/components/UseXAgent.vue')['default']
    UseXChat: typeof import('./src/components/UseXChat.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
    XProvider: typeof import('./src/components/XProvider.vue')['default']
    XRequest: typeof import('./src/components/XRequest.vue')['default']
    XStream: typeof import('./src/components/XStream.vue')['default']
  }
}
