/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AXBubble: typeof import('ant-design-x-vue')['Bubble']
    Bubble: typeof import('./src/components/Bubble.vue')['default']
    Conversations: typeof import('./src/components/Conversations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
